name: CI/CD Pipeline

on:
  push:
    branches-ignore:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v2

    # Set up Docker Buildx (for building Docker images)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Log in to Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT }}
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        export_default_credentials: true

    # Build the Docker image
    - name: Build Docker Image
      run: |
        docker build -t gcr.io/${{ secrets.GCLOUD_PROJECT }}/nestjs-api:$GITHUB_SHA .
      
    # Push Docker image to Google Container Registry
    - name: Push to Google Container Registry
      run: |
        docker push gcr.io/${{ secrets.GCLOUD_PROJECT }}/nestjs-api:$GITHUB_SHA

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

    # Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT }}
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        export_default_credentials: true

    # Deploy to Google Cloud
    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy nestjs-api \
        --image=gcr.io/${{ secrets.GCLOUD_PROJECT }}/nestjs-api:$GITHUB_SHA \
        --region=${{ secrets.GCLOUD_COMPUTE_ZONE }} \
        --platform managed \
        --allow-unauthenticated
